Name:           ros-jade-freefloating-gazebo
Version:        1.0.3
Release:        0%{?dist}
Summary:        ROS freefloating_gazebo package

Group:          Development/Libraries
License:        BSD
URL:            https://github.com/freefloating-gazebo/freefloating_gazebo
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-control-toolbox
Requires:       ros-jade-gazebo-ros
Requires:       ros-jade-message-runtime
Requires:       ros-jade-rostime
Requires:       ros-jade-urdf
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-control-toolbox
BuildRequires:  ros-jade-gazebo-ros
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-rostime
BuildRequires:  ros-jade-urdf

%description
A plugin to simulate underwater vehicles in Gazebo and visualise with UWsim.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Thu Dec 03 2015 Olivier Kermorgant <olivier_kermorgant@yahoo.fr> - 1.0.3-0
- Autogenerated by Bloom

